# Generated by Django 2.2.17 on 2021-01-23 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='')),
                ('Title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('link', models.CharField(max_length=500)),
            ],
        ),
    ]
